#!/usr/bin/env bash


changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_and_run() {
       echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

check_and_run requirements.txt  "pip install -r ~/dev/kpi_factory/DeveloperTools/requirements.txt"

echo installed requirements

pip install Trax -I --find-links https://s3.amazonaws.com/trax-pypi/Trax/index.html

echo installed Trx

pip install KPIUtils-v2 -I --find-links https://s3.amazonaws.com/trax-pypi/KPIUtils-v2/index.html

echo installed KPIUtils