#!/usr/bin/env bash

# Author: Yoav Amir
# git hook to run a command after `git pull/merge`
echo ""
echo ==========================
echo "PS GIT post-merge hook"
echo ==========================

pip install -r requirements.txt

pip install -U Trax --find-links https://s3.amazonaws.com/trax-pypi/Trax/index.html

pip install -U KPIUtils --find-links https://s3.amazonaws.com/trax-pypi/KPIUtils/index.html

pip install -U KPIUtils-v2 --find-links https://s3.amazonaws.com/trax-pypi/KPIUtils-v2/index.html

echo "installed all necessary packages"