# kpi results
FK = 'fk'
NUMERATOR_ID = 'numerator_id'
NUMERATOR_RESULT = 'numerator_result'
DENOMINATOR_ID = 'denominator_id'
DENOMINATOR_RESULT = 'denominator_result'
RESULT = 'result'
CONTEXT_ID = 'context_id'

# kpi specs keys
NAME = 'name'
TEMPLATE = 'template'
MANUFACTURER = 'manufacturer'
CATEGORY = 'category'
PRODUCT = 'product'
RESULTS = 'results'
DATASET_A = 'dataset_a'
TEST_A = 'test_a'
FACINGS = 'facings'

COMPLIANT_BAY_COUNT = 'Compliant Bay Count'
SCENE_AVAILABILITY = 'Scene Availability'
FACINGS_SOS = 'Facings SOS'
SHARE_OF_SCENES = 'Share of Scenes'

# db columns
SCENE_FK = 'scene_fk'
PRODUCT_FK = 'product_fk'
PRODUCT_NAME = 'product_name'
TEMPLATE_FK = 'template_fk'

# template keys
MAIN_COOLERS = 'main_coolers'
SELF_COOLERS = 'self_coolers'
DISPLAY = 'display'
ENDCAP = 'display_endcap'
FRONT_ENTRANCE = 'front_entrance'
BEVERAGE_AISLE = 'beverage_aisle'

# manufacturer keys
COKE = 'coke'
FAIRLIFE = 'fairlife'
PEPSI = 'pepsi'

#
KPI_NAME = 'KPI Name'
EMPTY = 'empty'
QUESTION_TEXT = 'question_text'
FILTER = 'filter'
FILTERS = 'filters'
NUMERATOR = 'numerator'
DENOMINATOR = 'denominator'
CONTEXT = 'context'
KEY_PACKAGE = 'KEY PACKAGE'
TEMPLATE_NAME = 'template_name'
IDENTIFIER_PARENT = 'identifier_parent'
IDENTIFIER_RESULT = 'identifier_result'
KPI_ID = 'KPI ID'
KPI_PARENT_ID = 'KPI Parent ID'

KPI = 'KPI'
KPI_TYPE = 'KPI Type'
SHOULD_ENTER = 'should_enter'
LOCATION = 'location'
PRODUCT_TYPE = 'product_type'
CATEGORY_FK = 'category_fk'
MANUFACTURER_FK = 'manufacturer_fk'
NUMERATOR_ENTITY = 'Numerator Entity'
DENOMINATOR_ENTITY = 'Denominator Entity'
BAY_NUMBER = 'bay_number'
SCENE_MATCH_FK = 'scene_match_fk'
COUNT = 'count'
REGION = 'Military'
BRAND_FK = 'brand_fk'
