import datetime
import pandas as pd
from numpy import nan

__author__ = 'Dudi S'


class DataTestUnitMarsUk(object):

    static_data = pd.DataFrame.from_records(
        [{'atomic_kpi_fk': 465.0,
          'atomic_kpi_name': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,', 'kpi_fk': 96,
          'kpi_name': u'Sheba', 'kpi_set_fk': 7, 'kpi_set_name': u'ASSORTMENT SCORE'},
         {'atomic_kpi_fk': 466.0, 'atomic_kpi_name': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,',
          'kpi_fk': 96, 'kpi_name': u'Sheba', 'kpi_set_fk': 7, 'kpi_set_name': u'ASSORTMENT SCORE'},
         {'atomic_kpi_fk': 467.0,
          'atomic_kpi_name': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk', 'kpi_fk': 97,
          'kpi_name': u'Whi Pouch', 'kpi_set_fk': 7, 'kpi_set_name': u'ASSORTMENT SCORE'},
         {'atomic_kpi_fk': 468.0, 'atomic_kpi_name': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
          'kpi_fk': 97, 'kpi_name': u'Whi Pouch', 'kpi_set_fk': 7, 'kpi_set_name': u'ASSORTMENT SCORE'},
         {'atomic_kpi_fk': 469.0, 'atomic_kpi_name': u'Sheba', 'kpi_fk': 99, 'kpi_name': u'Sheba', 'kpi_set_fk': 8,
          'kpi_set_name': u'Share of Shelf SCORE'},
         {'atomic_kpi_fk': 470.0, 'atomic_kpi_name': u'Whi Pouch', 'kpi_fk': 100, 'kpi_name': u'Whi Pouch',
          'kpi_set_fk': 8, 'kpi_set_name': u'Share of Shelf SCORE'},
         {'atomic_kpi_fk': 475.0, 'atomic_kpi_name': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
          'kpi_fk': 105, 'kpi_name': u'Sheba', 'kpi_set_fk': 10,
          'kpi_set_name': u'Position on Shelf - Position score'},
         {'atomic_kpi_fk': 476.0, 'atomic_kpi_name': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,',
          'kpi_fk': 105, 'kpi_name': u'Sheba', 'kpi_set_fk': 10,
          'kpi_set_name': u'Position on Shelf - Position score'},
         {'atomic_kpi_fk': 477.0,
          'atomic_kpi_name': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk', 'kpi_fk': 106,
          'kpi_name': u'Whi Pouch', 'kpi_set_fk': 10, 'kpi_set_name': u'Position on Shelf - Position score'},
         {'atomic_kpi_fk': 478.0,
          'atomic_kpi_name': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk', 'kpi_fk': 106,
          'kpi_name': u'Whi Pouch', 'kpi_set_fk': 10, 'kpi_set_name': u'Position on Shelf - Position score'},
         {'atomic_kpi_fk': 479.0, 'atomic_kpi_name': u'Dreamies', 'kpi_fk': 108, 'kpi_name': u'Dreamies',
          'kpi_set_fk': 11, 'kpi_set_name': u'Clip strips Score'},
         {'atomic_kpi_fk': 480.0, 'atomic_kpi_name': u'Ped - 1st SKU', 'kpi_fk': 109, 'kpi_name': u'Ped - 1st SKU',
          'kpi_set_fk': 11, 'kpi_set_name': u'Clip strips Score'},
         {'atomic_kpi_fk': 481.0, 'atomic_kpi_name': u'Sheba', 'kpi_fk': 111, 'kpi_name': u'Sheba',
          'kpi_set_fk': 12, 'kpi_set_name': u'Macro space KPI'},
         {'atomic_kpi_fk': 482.0, 'atomic_kpi_name': u'Whi Pouch', 'kpi_fk': 112, 'kpi_name': u'Whi Pouch',
          'kpi_set_fk': 12, 'kpi_set_name': u'Macro space KPI'},
         {'atomic_kpi_fk': nan, 'atomic_kpi_name': None, 'kpi_fk': 95, 'kpi_name': u'ASSORTMENT SCORE',
          'kpi_set_fk': 6, 'kpi_set_name': u'PERFECT STORE'},
         {'atomic_kpi_fk': nan, 'atomic_kpi_name': None, 'kpi_fk': 98, 'kpi_name': u'Share of Shelf SCORE',
          'kpi_set_fk': 6, 'kpi_set_name': u'PERFECT STORE'},
         {'atomic_kpi_fk': nan, 'atomic_kpi_name': None, 'kpi_fk': 101,
          'kpi_name': u'Position on Shelf  - Facing Score', 'kpi_set_fk': 6, 'kpi_set_name': u'PERFECT STORE'},
         {'atomic_kpi_fk': nan, 'atomic_kpi_name': None, 'kpi_fk': 104,
          'kpi_name': u'Position on Shelf - Position score', 'kpi_set_fk': 6, 'kpi_set_name': u'PERFECT STORE'},
         {'atomic_kpi_fk': nan, 'atomic_kpi_name': None, 'kpi_fk': 107, 'kpi_name': u'Clip strips Score',
          'kpi_set_fk': 6, 'kpi_set_name': u'PERFECT STORE'},
         {'atomic_kpi_fk': nan, 'atomic_kpi_name': None, 'kpi_fk': 110, 'kpi_name': u'Macro space KPI',
          'kpi_set_fk': 6, 'kpi_set_name': u'PERFECT STORE'}]
    )

    assortment_data = pd.DataFrame.from_records([
        {u'Atomic Kpi NAME': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 1, u'Include in Scoring': '', u'KPI Name': u'Sheba',
         u'Product List (KPI Name)': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
         u'Products EANs': 4770608247003, u'Supermarket': 1, u'score group': ''},
        {u'Atomic Kpi NAME': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,', u'Grocery Convenience 1 Bay': '',
         u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1, u'Hypermarket': 1,
         u'Include in Scoring': '', u'KPI Name': u'Sheba',
         u'Product List (KPI Name)': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,',
         u'Products EANs': 3065890099692, u'Supermarket': 1, u'score group': ''},
        {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 1, u'Include in Scoring': '', u'KPI Name': u'Whi Pouch',
         u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
         u'Products EANs': 5900951112935, u'Supermarket': 1, u'score group': 50.0},
        {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 1, u'Include in Scoring': '', u'KPI Name': u'Whi Pouch',
         u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
         u'Products EANs': 5900951113758, u'Supermarket': 1, u'score group': 100.0}
    ])

    hierarchy_duplicated_atomic_kpi_data = pd.DataFrame.from_records([
        {u'Atomic Kpi NAME': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': '', u'Include in Scoring': '', u'KPI Name': u'Sheba',
         u'Product List (KPI Name)': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
         u'Products EANs': 4770608247003, u'Supermarket': 1, u'score group': ''},
        {u'Atomic Kpi NAME': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 3, u'Include in Scoring': '', u'KPI Name': u'Sheba',
         u'Product List (KPI Name)': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
         u'Products EANs': 4770608247003, u'Supermarket': 1, u'score group': ''},
        {u'Atomic Kpi NAME': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,', u'Grocery Convenience 1 Bay': '',
         u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1, u'Hypermarket': 1,
         u'Include in Scoring': '', u'KPI Name': u'Sheba',
         u'Product List (KPI Name)': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,',
         u'Products EANs': 3065890099692, u'Supermarket': 1, u'score group': ''},
        {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 1, u'Include in Scoring': '', u'KPI Name': u'Whi Pouch',
         u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
         u'Products EANs': 5900951112935, u'Supermarket': 1, u'score group': 50.0},
        {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 1, u'Include in Scoring': '', u'KPI Name': u'Whi Pouch',
         u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
         u'Products EANs': 5900951113758, u'Supermarket': 1, u'score group': 100.0}
    ])

    num_of_facings_atomic_kpi_data = pd.DataFrame.from_records([
        {u'Atomic Kpi NAME': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 3, u'Include in Scoring': '', u'KPI Name': u'Sheba',
         u'Product List (KPI Name)': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
         u'Products EANs': 4770608247003, u'Supermarket': 1, u'score group': ''},
        {u'Atomic Kpi NAME': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,', u'Grocery Convenience 1 Bay': '',
         u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1, u'Hypermarket': 1,
         u'Include in Scoring': '', u'KPI Name': u'Sheba',
         u'Product List (KPI Name)': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,',
         u'Products EANs': 3065890099692, u'Supermarket': 1, u'score group': ''},
        {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 1, u'Include in Scoring': '', u'KPI Name': u'Whi Pouch',
         u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
         u'Products EANs': 5900951112935, u'Supermarket': 1, u'score group': 50.0},
        {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 1, u'Include in Scoring': '', u'KPI Name': u'Whi Pouch',
         u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
         u'Products EANs': 5900951113758, u'Supermarket': 1, u'score group': 100.0}
    ])

    sos_atomic_kpi_data = pd.DataFrame.from_records(
        [{u'Atomic Kpi NAME': u'Sheba',
          u'Denominator': u'Cat Superpremium',
          u'Entity Type Denominator': u'Sub-Category',
          u'Entity Type Numerator': u'Brand',
          u'Grocery Convenience 1 Bay': 50,
          u'Grocery Convenience 2 Bay': 50,
          u'Grocery Convenience 3 Bay': 52,
          u'Hypermarket': 41,
          u'Include in Scoring': '',
          u'KPI Name': u'Sheba',
          u'Numerator': u'Sheba',
          u'Supermarket': 39},
         ]
    )

    shelves_atomic_kpi_data = pd.DataFrame.from_records(
        [{u'Atomic Kpi NAME': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
          u'Grocery Convenience 1 Bay': 1,
          u'Grocery Convenience 2 Bay': 1,
          u'Grocery Convenience 3 Bay': 1,
          u'Hypermarket': u'2,3,4',
          u'Include in Scoring': '',
          u'KPI Name': u'Sheba',
          u'Product List (KPI Name)': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
          u'Products EANs': 4770608247003,
          u'Supermarket': u'2,3,4',
          u'score group': 100},
         {u'Atomic Kpi NAME': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,',
          u'Grocery Convenience 1 Bay': '',
          u'Grocery Convenience 2 Bay': 1,
          u'Grocery Convenience 3 Bay': 1,
          u'Hypermarket': u'2,3,4',
          u'Include in Scoring': '',
          u'KPI Name': u'Sheba',
          u'Product List (KPI Name)': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,',
          u'Products EANs': 3065890099692,
          u'Supermarket': u'2,3,4',
          u'score group': 100},
         {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
          u'Grocery Convenience 1 Bay': u'2,3',
          u'Grocery Convenience 2 Bay': u'3,4',
          u'Grocery Convenience 3 Bay': u'2,3',
          u'Hypermarket': u'2,3',
          u'Include in Scoring': '',
          u'KPI Name': u'Whi Pouch',
          u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
          u'Products EANs': 5900951112935,
          u'Supermarket': u'2,3',
          u'score group': 50},
         {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
          u'Grocery Convenience 1 Bay': u'2,3',
          u'Grocery Convenience 2 Bay': u'3,4',
          u'Grocery Convenience 3 Bay': u'2,3',
          u'Hypermarket': u'2,3',
          u'Include in Scoring': '',
          u'KPI Name': u'Whi Pouch',
          u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
          u'Products EANs': 5900951113758,
          u'Supermarket': u'2,3',
          u'score group': 50}]

    )

    sos_atomic_kpi_sub_category_only_data = pd.DataFrame.from_records(
        [{u'Atomic Kpi NAME': u'Sheba',
          u'Denominator': u'',
          u'Entity Type Denominator': u'',
          u'Entity Type Numerator': u'Sub-Category',
          u'Grocery Convenience 1 Bay': 50,
          u'Grocery Convenience 2 Bay': 50,
          u'Grocery Convenience 3 Bay': 52,
          u'Hypermarket': 51,
          u'Include in Scoring': '',
          u'KPI Name': u'Sheba',
          u'Numerator': u'Cat Superpremium',
          u'Supermarket': 39}]
    )

    shelves_kpi_data = pd.DataFrame.from_records(
        [
            {u'KPI Group': u'Position on Shelf - Position',
             u'KPI Type': u'Strict Shelf Level Position',
             u'KPI name Eng': u'Sheba',
             u'SCORE': u'BINARY',
             u'Scene Types to Include': u'Petcare Main Shelves',
             u'Target': u'SEE Shelves_Pos_Products',
             u'Tested KPI Group': '',
             u'WEIGHT': 3.0},
            {u'KPI Group': u'PERFECT STORE',
             u'KPI Type': u'Weighted SUM KPIs in GROUP',
             u'KPI name Eng': u'Position on Shelf - Position score',
             u'SCORE': u'SUM OF SCORES',
             u'Scene Types to Include': '',
             u'Target': '',
             u'Tested KPI Group': u'Position on Shelf - Position',
             u'WEIGHT': ''},
            {u'KPI Group': '',
             u'KPI Type': u'Weighted SUM KPIs in GROUP',
             u'KPI name Eng': u'PERFECT STORE',
             u'SCORE': u'SUM OF SCORES',
             u'Scene Types to Include': '',
             u'Target': '',
             u'Tested KPI Group': u'PERFECT STORE',
             u'WEIGHT': ''}

        ]
    )

    shelves_kpi_data_with_different_scene_type_filter = pd.DataFrame.from_records(
        [
            {u'KPI Group': u'Position on Shelf - Position',
             u'KPI Type': u'Strict Shelf Level Position',
             u'KPI name Eng': u'Sheba',
             u'SCORE': u'BINARY',
             u'Scene Types to Include': u'different_scene_type',
             u'Target': u'SEE Shelves_Pos_Products',
             u'Tested KPI Group': '',
             u'WEIGHT': 3.0},
            {u'KPI Group': u'PERFECT STORE',
             u'KPI Type': u'Weighted SUM KPIs in GROUP',
             u'KPI name Eng': u'Position on Shelf - Position score',
             u'SCORE': u'SUM OF SCORES',
             u'Scene Types to Include': '',
             u'Target': '',
             u'Tested KPI Group': u'Position on Shelf - Position',
             u'WEIGHT': ''},
            {u'KPI Group': '',
             u'KPI Type': u'Weighted SUM KPIs in GROUP',
             u'KPI name Eng': u'PERFECT STORE',
             u'SCORE': u'SUM OF SCORES',
             u'Scene Types to Include': '',
             u'Target': '',
             u'Tested KPI Group': u'PERFECT STORE',
             u'WEIGHT': ''}

        ]
    )

    clip_strip_kpi_data = pd.DataFrame.from_records([
        {u'KPI Group': u'Clip strips',
         u'KPI Type': u'Clip strips facings',
         u'KPI name Eng': u'Dreamies',
         u'SCORE': u'BINARY',
         u'Scene Types to Include': u'',
         u'Target': u'SEE Clip_Strips',
         u'Tested KPI Group': '',
         u'WEIGHT': 1.0},
        {u'KPI Group': u'PERFECT STORE',
         u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'Clip strips Score',
         u'SCORE': u'SUM OF SCORES',
         u'Scene Types to Include': '',
         u'Target': '',
         u'Tested KPI Group': u'Clip strips',
         u'WEIGHT': ''},
        {u'KPI Group': '',
         u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'PERFECT STORE',
         u'SCORE': u'SUM OF SCORES',
         u'Scene Types to Include': '',
         u'Target': '',
         u'Tested KPI Group': u'PERFECT STORE',
         u'WEIGHT': ''}
    ])

    clip_strip_kpi_data_with_scene_type_filter = pd.DataFrame.from_records([
        {u'KPI Group': u'Clip strips',
         u'KPI Type': u'Clip strips facings',
         u'KPI name Eng': u'Dreamies',
         u'SCORE': u'BINARY',
         u'Scene Types to Include': u'Petcare Main Shelves',
         u'Target': u'SEE Clip_Strips',
         u'Tested KPI Group': '',
         u'WEIGHT': 1.0},
        {u'KPI Group': u'PERFECT STORE',
         u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'Clip strips Score',
         u'SCORE': u'SUM OF SCORES',
         u'Scene Types to Include': '',
         u'Target': '',
         u'Tested KPI Group': u'Clip strips',
         u'WEIGHT': ''},
        {u'KPI Group': '',
         u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'PERFECT STORE',
         u'SCORE': u'SUM OF SCORES',
         u'Scene Types to Include': '',
         u'Target': '',
         u'Tested KPI Group': u'PERFECT STORE',
         u'WEIGHT': ''}
    ])

    full_kpi = pd.DataFrame.from_records(
        [{u'KPI Group': u'ASSORTMENT',
          u'KPI Type': u'Num Of Facings',
          u'KPI name Eng': u'Sheba',
          u'SCORE': u'BINARY',
          u'Scene Types to Include': '',
          u'Target': u'SEE ASSORTMENT',
          u'Tested KPI Group': '',
          u'WEIGHT': 3.0},
         {u'KPI Group': u'ASSORTMENT',
          u'KPI Type': u'Num Of Facings',
          u'KPI name Eng': u'Whi Pouch',
          u'SCORE': u'ACCUMULATIVE',
          u'Scene Types to Include': '',
          u'Target': u'SEE ASSORTMENT',
          u'Tested KPI Group': '',
          u'WEIGHT': 6.0},
         {u'KPI Group': u'Share of Shelf',
          u'KPI Type': u'SOS Linear',
          u'KPI name Eng': u'Sheba',
          u'SCORE': u'BINARY',
          u'Scene Types to Include': '',
          u'Target': u'SEE SOS_Targets',
          u'Tested KPI Group': '',
          u'WEIGHT': 3.0},
         {u'KPI Group': u'Share of Shelf',
          u'KPI Type': u'SOS Linear',
          u'KPI name Eng': u'Whi Pouch',
          u'SCORE': u'BINARY',
          u'Scene Types to Include': '',
          u'Target': u'SEE SOS_Targets',
          u'Tested KPI Group': '',
          u'WEIGHT': 4.0},
         {u'KPI Group': u'Position on Shelf - Facing',
          u'KPI Type': u'Num Of Facings',
          u'KPI name Eng': u'Sheba',
          u'SCORE': u'PROPORTIONAL',
          u'Scene Types to Include': '',
          u'Target': u'SEE Facings_Targets',
          u'Tested KPI Group': '',
          u'WEIGHT': 1.0},
         {u'KPI Group': u'Position on Shelf - Facing',
          u'KPI Type': u'Num Of Facings',
          u'KPI name Eng': u'Whi Pouch',
          u'SCORE': u'PROPORTIONAL BY GROUPS',
          u'Scene Types to Include': '',
          u'Target': u'SEE Facings_Targets',
          u'Tested KPI Group': '',
          u'WEIGHT': 2.0},
         {u'KPI Group': u'Position on Shelf - Position',
          u'KPI Type': u'Strict Shelf Level Position',
          u'KPI name Eng': u'Sheba',
          u'SCORE': u'BINARY',
          u'Scene Types to Include': '',
          u'Target': u'SEE Shelves_Pos_Products',
          u'Tested KPI Group': '',
          u'WEIGHT': 3.0},
         {u'KPI Group': u'Position on Shelf - Position',
          u'KPI Type': u'Strict Shelf Level Position',
          u'KPI name Eng': u'Whi Pouch',
          u'SCORE': u'BINARY',
          u'Scene Types to Include': '',
          u'Target': u'SEE Shelves_Pos_Products',
          u'Tested KPI Group': '',
          u'WEIGHT': 5.0},
         {u'KPI Group': u'Clip strips',
          u'KPI Type': u'Clip strips facings',
          u'KPI name Eng': u'Dreamies',
          u'SCORE': u'BINARY',
          u'Scene Types to Include': '',
          u'Target': u'SEE Clip_Strips',
          u'Tested KPI Group': '',
          u'WEIGHT': 1.0},
         {u'KPI Group': u'Clip strips',
          u'KPI Type': u'Clip strips facings',
          u'KPI name Eng': u'Ped - 1st SKU',
          u'SCORE': u'BINARY',
          u'Scene Types to Include': '',
          u'Target': u'SEE Clip_Strips',
          u'Tested KPI Group': '',
          u'WEIGHT': 0.5},
         {u'KPI Group': u'Macro Space',
          u'KPI Type': u'SOS Linear',
          u'KPI name Eng': u'Sheba',
          u'SCORE': u'BINARY',
          u'Scene Types to Include': '',
          u'Target': u'SEE Macro_Spaces_Targets',
          u'Tested KPI Group': '',
          u'WEIGHT': 1.0},
         {u'KPI Group': u'Macro Space',
          u'KPI Type': u'SOS Linear',
          u'KPI name Eng': u'Whi Pouch',
          u'SCORE': u'BINARY',
          u'Scene Types to Include': '',
          u'Target': u'SEE Macro_Spaces_Targets',
          u'Tested KPI Group': '',
          u'WEIGHT': 1.0},
         {u'KPI Group': u'PERFECT STORE',
          u'KPI Type': u'Weighted SUM KPIs in GROUP',
          u'KPI name Eng': u'ASSORTMENT SCORE',
          u'SCORE': u'SUM OF SCORES',
          u'Scene Types to Include': '',
          u'Target': '',
          u'Tested KPI Group': u'ASSORTMENT',
          u'WEIGHT': ''},
         {u'KPI Group': u'PERFECT STORE',
          u'KPI Type': u'Weighted SUM KPIs in GROUP',
          u'KPI name Eng': u'Share of Shelf SCORE',
          u'SCORE': u'SUM OF SCORES',
          u'Scene Types to Include': '',
          u'Target': '',
          u'Tested KPI Group': u'Share of Shelf',
          u'WEIGHT': ''},
         {u'KPI Group': u'PERFECT STORE',
          u'KPI Type': u'Weighted SUM KPIs in GROUP',
          u'KPI name Eng': u'Position on Shelf  - Facing Score',
          u'SCORE': u'SUM OF SCORES',
          u'Scene Types to Include': '',
          u'Target': '',
          u'Tested KPI Group': u'Position on Shelf - Facing',
          u'WEIGHT': ''},
         {u'KPI Group': u'PERFECT STORE',
          u'KPI Type': u'Weighted SUM KPIs in GROUP',
          u'KPI name Eng': u'Position on Shelf - Position score',
          u'SCORE': u'SUM OF SCORES',
          u'Scene Types to Include': '',
          u'Target': '',
          u'Tested KPI Group': u'Position on Shelf - Position',
          u'WEIGHT': ''},
         {u'KPI Group': u'PERFECT STORE',
          u'KPI Type': u'Weighted SUM KPIs in GROUP',
          u'KPI name Eng': u'Clip strips Score',
          u'SCORE': u'SUM OF SCORES',
          u'Scene Types to Include': '',
          u'Target': '',
          u'Tested KPI Group': u'Clip strips',
          u'WEIGHT': ''},
         {u'KPI Group': u'PERFECT STORE',
          u'KPI Type': u'Weighted SUM KPIs in GROUP',
          u'KPI name Eng': u'Macro space KPI',
          u'SCORE': u'SUM OF SCORES',
          u'Scene Types to Include': '',
          u'Target': '',
          u'Tested KPI Group': u'Macro Space',
          u'WEIGHT': ''},
         {u'KPI Group': '',
          u'KPI Type': u'Weighted SUM KPIs in GROUP',
          u'KPI name Eng': u'PERFECT STORE',
          u'SCORE': u'SUM OF SCORES',
          u'Scene Types to Include': '',
          u'Target': '',
          u'Tested KPI Group': u'PERFECT STORE',
          u'WEIGHT': ''}]

    )

    sos_kpi_data = pd.DataFrame.from_records([
         {u'KPI Group': u'Share of Shelf',
          u'KPI Type': u'SOS Linear',
          u'KPI name Eng': u'Sheba',
          u'SCORE': u'BINARY',
          u'Scene Types to Include': '',
          u'Target': u'SEE SOS_Targets',
          u'Tested KPI Group': '',
          u'WEIGHT': 3.0},
         {u'KPI Group': u'PERFECT STORE',
          u'KPI Type': u'Weighted SUM KPIs in GROUP',
          u'KPI name Eng': u'Share of Shelf SCORE',
          u'SCORE': u'SUM OF SCORES',
          u'Scene Types to Include': '',
          u'Target': '',
          u'Tested KPI Group': u'Share of Shelf',
          u'WEIGHT': ''},
         {u'KPI Group': '',
          u'KPI Type': u'Weighted SUM KPIs in GROUP',
          u'KPI name Eng': u'PERFECT STORE',
          u'SCORE': u'SUM OF SCORES',
          u'Scene Types to Include': '',
          u'Target': '',
          u'Tested KPI Group': u'PERFECT STORE',
          u'WEIGHT': ''}
    ])

    sos_kpi_data_with_scene_type = pd.DataFrame.from_records([
        {u'KPI Group': u'Share of Shelf',
         u'KPI Type': u'SOS Linear',
         u'KPI name Eng': u'Sheba',
         u'SCORE': u'BINARY',
         u'Scene Types to Include': u'Petcare Main Shelves',
         u'Target': u'SEE SOS_Targets',
         u'Tested KPI Group': '',
         u'WEIGHT': 3.0},
        {u'KPI Group': u'PERFECT STORE',
         u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'Share of Shelf SCORE',
         u'SCORE': u'SUM OF SCORES',
         u'Scene Types to Include': '',
         u'Target': '',
         u'Tested KPI Group': u'Share of Shelf',
         u'WEIGHT': ''},
        {u'KPI Group': '',
         u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'PERFECT STORE',
         u'SCORE': u'SUM OF SCORES',
         u'Scene Types to Include': '',
         u'Target': '',
         u'Tested KPI Group': u'PERFECT STORE',
         u'WEIGHT': ''}
    ])

    atomic_kpi_data_for_excluded = pd.DataFrame.from_records([
        {u'Atomic Kpi NAME': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 1, u'Include in Scoring': 'No', u'KPI Name': u'Sheba',
         u'Product List (KPI Name)': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
         u'Products EANs': 4770608247003, u'Supermarket': 1, u'score group': ''},
        {u'Atomic Kpi NAME': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,', u'Grocery Convenience 1 Bay': '',
         u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1, u'Hypermarket': 1,
         u'Include in Scoring': '', u'KPI Name': u'Sheba',
         u'Product List (KPI Name)': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,',
         u'Products EANs': 3065890099692, u'Supermarket': 1, u'score group': ''},
        {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 1, u'Include in Scoring': '', u'KPI Name': u'Whi Pouch',
         u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
         u'Products EANs': 5900951112935, u'Supermarket': 1, u'score group': 50.0},
        {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 1, u'Include in Scoring': '', u'KPI Name': u'Whi Pouch',
         u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
         u'Products EANs': 5900951113758, u'Supermarket': 1, u'score group': 100.0}
    ])

    accumulative_scoring_atomic_data = pd.DataFrame.from_records([
        {u'Atomic Kpi NAME': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 1, u'Include in Scoring': '', u'KPI Name': u'Whi Pouch',
         u'Product List (KPI Name)': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
         u'Products EANs': 4770608247003, u'Supermarket': 1, u'score group': 50},
        {u'Atomic Kpi NAME': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,', u'Grocery Convenience 1 Bay': '',
         u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1, u'Hypermarket': 1,
         u'Include in Scoring': '', u'KPI Name': u'Whi Pouch',
         u'Product List (KPI Name)': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,',
         u'Products EANs': 3065890099692, u'Supermarket': 1, u'score group': 50},
        {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 1, u'Include in Scoring': '', u'KPI Name': u'Whi Pouch',
         u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
         u'Products EANs': 5900951112935, u'Supermarket': 1, u'score group': 100},
        {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
         u'Grocery Convenience 1 Bay': 1.0, u'Grocery Convenience 2 Bay': 1, u'Grocery Convenience 3 Bay': 1,
         u'Hypermarket': 1, u'Include in Scoring': '', u'KPI Name': u'Whi Pouch',
         u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
         u'Products EANs': 5900951113758, u'Supermarket': 1, u'score group': 100}
    ])

    proportional_group_atomic_kpi_data = pd.DataFrame(
        [{u'Atomic Kpi NAME': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
          u'Grocery Convenience 1 Bay': 2.0,
          u'Grocery Convenience 2 Bay': 2,
          u'Grocery Convenience 3 Bay': 2,
          u'Hypermarket': 2,
          u'Include in Scoring': '',
          u'KPI Name': u'Sheba',
          u'Product List (KPI Name)': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
          u'Products EANs': 4770608247003,
          u'Supermarket': 2,
          u'group weight': 50,
          u'score group': 1},
         {u'Atomic Kpi NAME': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,',
          u'Grocery Convenience 1 Bay': '',
          u'Grocery Convenience 2 Bay': 1,
          u'Grocery Convenience 3 Bay': 1,
          u'Hypermarket': 2,
          u'Include in Scoring': '',
          u'KPI Name': u'Sheba',
          u'Product List (KPI Name)': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,',
          u'Products EANs': 3065890099692,
          u'Supermarket': 2,
          u'group weight': 50,
          u'score group': 1},
         {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
          u'Grocery Convenience 1 Bay': 1.0,
          u'Grocery Convenience 2 Bay': 1,
          u'Grocery Convenience 3 Bay': 1,
          u'Hypermarket': 2,
          u'Include in Scoring': '',
          u'KPI Name': u'Sheba',
          u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
          u'Products EANs': 5900951112935,
          u'Supermarket': 2,
          u'group weight': 25.0,
          u'score group': 2},
         {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
          u'Grocery Convenience 1 Bay': 1.0,
          u'Grocery Convenience 2 Bay': 1,
          u'Grocery Convenience 3 Bay': 1,
          u'Hypermarket': 2,
          u'Include in Scoring': '',
          u'KPI Name': u'Sheba',
          u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
          u'Products EANs': 5900951113758,
          u'Supermarket': 2,
          u'group weight': 25.0,
          u'score group': 2}]

    )

    clip_strip_atomic_kpi_data = pd.DataFrame.from_records(
        [{u'Atomic Kpi NAME': u'Dreamies',
          u'Brand Name': u'Dreamies',
          u'Grocery Convenience 1 Bay': '',
          u'Grocery Convenience 2 Bay': 1,
          u'Grocery Convenience 3 Bay': 1,
          u'Hypermarket': 1,
          u'Include in Scoring': '',
          u'KPI Name': u'Dreamies',
          u'Product Type': u'CE',
          u'Supermarket': 1,
          u'score group': 100},
         {u'Atomic Kpi NAME': u'Ped - 1st SKU',
          u'Brand Name': u'Ped',
          u'Grocery Convenience 1 Bay': 1.0,
          u'Grocery Convenience 2 Bay': 1,
          u'Grocery Convenience 3 Bay': 1,
          u'Hypermarket': 1,
          u'Include in Scoring': '',
          u'KPI Name': u'Ped - 1st SKU',
          u'Product Type': u'CE',
          u'Supermarket': 1,
          u'score group': 100}]

    )

    facings_atomic_kpi_data_with_test_store_type = pd.DataFrame(
        [{u'Atomic Kpi NAME': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
          u'Grocery Convenience 1 Bay': 2.0,
          u'Grocery Convenience 2 Bay': 2,
          u'Grocery Convenience 3 Bay': 2,
          u'Hypermarket_test': 2,
          u'Include in Scoring': '',
          u'KPI Name': u'Sheba',
          u'Product List (KPI Name)': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6,',
          u'Products EANs': 4770608247003,
          u'Supermarket': 2,
          u'group weight': 50,
          u'score group': 1},
         {u'Atomic Kpi NAME': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,',
          u'Grocery Convenience 1 Bay': '',
          u'Grocery Convenience 2 Bay': 1,
          u'Grocery Convenience 3 Bay': 1,
          u'Hypermarket_test': 2,
          u'Include in Scoring': '',
          u'KPI Name': u'Sheba',
          u'Product List (KPI Name)': u'SHEBA POUCH FINE FLAKES POULTRY IN JELLY 85GX12,',
          u'Products EANs': 3065890099692,
          u'Supermarket': 2,
          u'group weight': 50,
          u'score group': 1},
         {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
          u'Grocery Convenience 1 Bay': 1.0,
          u'Grocery Convenience 2 Bay': 1,
          u'Grocery Convenience 3 Bay': 1,
          u'Hypermarket_test': 2,
          u'Include in Scoring': '',
          u'KPI Name': u'Sheba',
          u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Poultry Selection in Jelly 12x100g pk',
          u'Products EANs': 5900951112935,
          u'Supermarket': 2,
          u'group weight': 25.0,
          u'score group': 2},
         {u'Atomic Kpi NAME': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
          u'Grocery Convenience 1 Bay': 1.0,
          u'Grocery Convenience 2 Bay': 1,
          u'Grocery Convenience 3 Bay': 1,
          u'Hypermarket_test': 2,
          u'Include in Scoring': '',
          u'KPI Name': u'Sheba',
          u'Product List (KPI Name)': u'WHISKAS 1+ Cat Pouches Fish Selection in Jelly 12x100g pk',
          u'Products EANs': 5900951113758,
          u'Supermarket': 2,
          u'group weight': 25.0,
          u'score group': 2}])

    accumulative_scoring_kpi_data = pd.DataFrame.from_records([
        {u'KPI Group': u'ASSORTMENT', u'KPI Type': u'Num Of Facings', u'KPI name Eng': u'Whi Pouch',
         u'SCORE': u'ACCUMULATIVE', u'Scene Types to Include': '', u'Target': u'SEE ASSORTMENT',
         u'Tested KPI Group': '', u'WEIGHT': 6.0},
        {u'KPI Group': u'PERFECT STORE', u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'ASSORTMENT SCORE', u'SCORE': u'SUM OF SCORES', u'Scene Types to Include': '',
         u'Target': '', u'Tested KPI Group': u'ASSORTMENT', u'WEIGHT': ''},
        {u'KPI Group': '', u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'PERFECT STORE', u'SCORE': u'SUM OF SCORES', u'Scene Types to Include': '',
         u'Target': '', u'Tested KPI Group': u'PERFECT STORE', u'WEIGHT': ''}
    ])

    assortment_kpi_data = pd.DataFrame.from_records([
        {u'KPI Group': u'ASSORTMENT', u'KPI Type': u'Num Of Facings', u'KPI name Eng': u'Sheba',
         u'SCORE': u'BINARY', u'Scene Types to Include': '', u'Target': u'SEE ASSORTMENT',
         u'Tested KPI Group': '', u'WEIGHT': 3.0},
        {u'KPI Group': u'ASSORTMENT', u'KPI Type': u'Num Of Facings', u'KPI name Eng': u'Whi Pouch',
         u'SCORE': u'ACCUMULATIVE', u'Scene Types to Include': '', u'Target': u'SEE ASSORTMENT',
         u'Tested KPI Group': '', u'WEIGHT': 6.0},
        {u'KPI Group': u'PERFECT STORE', u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'ASSORTMENT SCORE', u'SCORE': u'SUM OF SCORES', u'Scene Types to Include': '',
         u'Target': '', u'Tested KPI Group': u'ASSORTMENT', u'WEIGHT': ''},
        {u'KPI Group': '', u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'PERFECT STORE', u'SCORE': u'SUM OF SCORES', u'Scene Types to Include': '',
         u'Target': '', u'Tested KPI Group': u'PERFECT STORE', u'WEIGHT': ''}
    ])

    hierarchy_duplicated_kpi_data = pd.DataFrame.from_records([
        {u'KPI Group': u'ASSORTMENT', u'KPI Type': u'Num Of Facings', u'KPI name Eng': u'Sheba',
         u'SCORE': u'BINARY', u'Scene Types to Include': '', u'Target': u'SEE ASSORTMENT',
         u'Tested KPI Group': '', u'WEIGHT': 3.0},
        {u'KPI Group': u'ASSORTMENT', u'KPI Type': u'Num Of Facings', u'KPI name Eng': u'Sheba',
         u'SCORE': u'BINARY', u'Scene Types to Include': '', u'Target': u'SEE ASSORTMENT',
         u'Tested KPI Group': '', u'WEIGHT': 3.0},
        {u'KPI Group': u'ASSORTMENT', u'KPI Type': u'Num Of Facings', u'KPI name Eng': u'Whi Pouch',
         u'SCORE': u'ACCUMULATIVE', u'Scene Types to Include': '', u'Target': u'SEE ASSORTMENT',
         u'Tested KPI Group': '', u'WEIGHT': 6.0},
        {u'KPI Group': u'PERFECT STORE', u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'ASSORTMENT SCORE', u'SCORE': u'SUM OF SCORES', u'Scene Types to Include': '',
         u'Target': '', u'Tested KPI Group': u'ASSORTMENT', u'WEIGHT': ''},
        {u'KPI Group': '', u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'PERFECT STORE', u'SCORE': u'SUM OF SCORES', u'Scene Types to Include': '',
         u'Target': '', u'Tested KPI Group': u'PERFECT STORE', u'WEIGHT': ''}
    ])

    assortment_kpi_data_with_scene_type_filter = pd.DataFrame.from_records([
        {u'KPI Group': u'ASSORTMENT', u'KPI Type': u'Num Of Facings', u'KPI name Eng': u'Sheba',
         u'SCORE': u'BINARY', u'Scene Types to Include': u'Petcare Main Shelves', u'Target': u'SEE ASSORTMENT',
         u'Tested KPI Group': '', u'WEIGHT': 3.0},
        {u'KPI Group': u'ASSORTMENT', u'KPI Type': u'Num Of Facings', u'KPI name Eng': u'Whi Pouch',
         u'SCORE': u'ACCUMULATIVE', u'Scene Types to Include': '', u'Target': u'SEE ASSORTMENT',
         u'Tested KPI Group': '', u'WEIGHT': 6.0},
        {u'KPI Group': u'PERFECT STORE', u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'ASSORTMENT SCORE', u'SCORE': u'SUM OF SCORES', u'Scene Types to Include': '',
         u'Target': '', u'Tested KPI Group': u'ASSORTMENT', u'WEIGHT': ''},
        {u'KPI Group': '', u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'PERFECT STORE', u'SCORE': u'SUM OF SCORES', u'Scene Types to Include': '',
         u'Target': '', u'Tested KPI Group': u'PERFECT STORE', u'WEIGHT': ''}
    ])

    assortment_and_facings_kpi_data = pd.DataFrame.from_records([
        {u'KPI Group': u'Position on Shelf - Facing',
         u'KPI Type': u'Num Of Facings',
         u'KPI name Eng': u'Sheba',
         u'SCORE': u'PROPORTIONAL BY GROUPS',
         u'Scene Types to Include': '',
         u'Target': u'SEE Facings_Targets',
         u'Tested KPI Group': '',
         u'WEIGHT': 1.0},
        {u'KPI Group': u'PERFECT STORE',
         u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'Position on Shelf  - Facing Score',
         u'SCORE': u'SUM OF SCORES',
         u'Scene Types to Include': '',
         u'Target': '',
         u'Tested KPI Group': u'Position on Shelf - Facing',
         u'WEIGHT': ''},
        {u'KPI Group': u'ASSORTMENT', u'KPI Type': u'Num Of Facings', u'KPI name Eng': u'Sheba',
         u'SCORE': u'BINARY', u'Scene Types to Include': '', u'Target': u'SEE ASSORTMENT',
         u'Tested KPI Group': '', u'WEIGHT': 3.0},
        {u'KPI Group': u'ASSORTMENT', u'KPI Type': u'Num Of Facings', u'KPI name Eng': u'Whi Pouch',
         u'SCORE': u'ACCUMULATIVE', u'Scene Types to Include': '', u'Target': u'SEE ASSORTMENT',
         u'Tested KPI Group': '', u'WEIGHT': 6.0},
        {u'KPI Group': u'PERFECT STORE', u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'ASSORTMENT SCORE', u'SCORE': u'SUM OF SCORES', u'Scene Types to Include': '',
         u'Target': '', u'Tested KPI Group': u'ASSORTMENT', u'WEIGHT': ''},
        {u'KPI Group': '', u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'PERFECT STORE', u'SCORE': u'SUM OF SCORES', u'Scene Types to Include': '',
         u'Target': '', u'Tested KPI Group': u'PERFECT STORE', u'WEIGHT': ''}
    ])

    proportional_kpi_data = pd.DataFrame.from_records([
        {u'KPI Group': u'ASSORTMENT', u'KPI Type': u'Num Of Facings', u'KPI name Eng': u'Sheba',
         u'SCORE': u'PROPORTIONAL', u'Scene Types to Include': '', u'Target': u'SEE ASSORTMENT',
         u'Tested KPI Group': '', u'WEIGHT': 3.0},
        {u'KPI Group': u'ASSORTMENT', u'KPI Type': u'Num Of Facings', u'KPI name Eng': u'Whi Pouch',
         u'SCORE': u'ACCUMULATIVE', u'Scene Types to Include': '', u'Target': u'SEE ASSORTMENT',
         u'Tested KPI Group': '', u'WEIGHT': 6.0},
        {u'KPI Group': u'PERFECT STORE', u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'ASSORTMENT SCORE', u'SCORE': u'SUM OF SCORES', u'Scene Types to Include': '',
         u'Target': '', u'Tested KPI Group': u'ASSORTMENT', u'WEIGHT': ''},
        {u'KPI Group': '', u'KPI Type': u'Weighted SUM KPIs in GROUP',
         u'KPI name Eng': u'PERFECT STORE', u'SCORE': u'SUM OF SCORES', u'Scene Types to Include': '',
         u'Target': '', u'Tested KPI Group': u'PERFECT STORE', u'WEIGHT': ''}
    ])

    proportional_group_kpi_data = pd.DataFrame.from_records([
         {u'KPI Group': u'Position on Shelf - Facing',
          u'KPI Type': u'Num Of Facings',
          u'KPI name Eng': u'Sheba',
          u'SCORE': u'PROPORTIONAL BY GROUPS',
          u'Scene Types to Include': '',
          u'Target': u'SEE Facings_Targets',
          u'Tested KPI Group': '',
          u'WEIGHT': 1.0},
         {u'KPI Group': u'PERFECT STORE',
          u'KPI Type': u'Weighted SUM KPIs in GROUP',
          u'KPI name Eng': u'Position on Shelf  - Facing Score',
          u'SCORE': u'SUM OF SCORES',
          u'Scene Types to Include': '',
          u'Target': '',
          u'Tested KPI Group': u'Position on Shelf - Facing',
          u'WEIGHT': ''},
         {u'KPI Group': '',
          u'KPI Type': u'Weighted SUM KPIs in GROUP',
          u'KPI name Eng': u'PERFECT STORE',
          u'SCORE': u'SUM OF SCORES',
          u'Scene Types to Include': '',
          u'Target': '',
          u'Tested KPI Group': u'PERFECT STORE',
          u'WEIGHT': ''}])

    scene_item_facts_product_4770608247003 = [
        {u'brand_name': u'Sheba',
          u'category_fk': 1,
          u'dist_sc': 1,
          u'facings': 2.0,
          u'facings_ign_stack': 2.0,
          'front_face_count': 1.0,
          u'gross_area_ign_stack': 34254.0,
          u'gross_area_split_stack': 35292.0,
          u'gross_len_add_stack': 173.0,
          u'gross_len_ign_stack': 173.0,
          u'gross_len_split_stack': 173.0,
          u'in_assort_sc': 0,
          u'is_sku': u'Y',
          u'location_type': u'Primary Shelf',
          u'manufacturer_name': u'Mars',
          u'product_ean_code': u'4770608247003',
          u'product_english_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
          u'product_fk': 761,
          u'product_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
          u'product_short_name': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
          u'product_type': u'SKU',
          u'rlv_dist_sc': 1,
          u'rlv_oos_sc': 1,
          u'rlv_sos_sc': 1,
          u'scene_fk': 14984,
          u'scene_id': 14984,
          u'sub_brand_name': None,
          u'sub_category': u'Cat Superpremium',
          u'template_display_name': u'Petcare Main Shelves',
          u'template_group': None,
          u'template_name': u'Tesco BB Hypermarket',
          u'visit_date': datetime.date(2017, 5, 23)}]

    scene_item_facts_product_4770608247003_different_scene_type = [
        {u'brand_name': u'Sheba',
         u'category_fk': 1,
         u'dist_sc': 1,
         u'facings': 2.0,
         u'facings_ign_stack': 2.0,
         'front_face_count': 1.0,
         u'gross_area_ign_stack': 34254.0,
         u'gross_area_split_stack': 35292.0,
         u'gross_len_add_stack': 173.0,
         u'gross_len_ign_stack': 173.0,
         u'gross_len_split_stack': 173.0,
         u'in_assort_sc': 0,
         u'is_sku': u'Y',
         u'location_type': u'Primary Shelf',
         u'manufacturer_name': u'Mars',
         u'product_ean_code': u'4770608247003',
         u'product_english_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_fk': 761,
         u'product_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_short_name': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_type': u'SKU',
         u'rlv_dist_sc': 1,
         u'rlv_oos_sc': 1,
         u'rlv_sos_sc': 1,
         u'scene_fk': 14984,
         u'scene_id': 14984,
         u'sub_brand_name': None,
         u'sub_category': u'Cat Superpremium',
         u'template_display_name': u'different_scene_type',
         u'template_group': None,
         u'template_name': u'Tesco BB Hypermarket',
         u'visit_date': datetime.date(2017, 5, 23)}]

    scene_item_facts_product_4770608247003_ce_dreamies = [
        {u'brand_name': u'Dreamies',
         u'category_fk': 1,
         u'dist_sc': 1,
         u'facings': 2.0,
         u'facings_ign_stack': 2.0,
         'front_face_count': 1.0,
         u'gross_area_ign_stack': 34254.0,
         u'gross_area_split_stack': 35292.0,
         u'gross_len_add_stack': 173.0,
         u'gross_len_ign_stack': 173.0,
         u'gross_len_split_stack': 173.0,
         u'in_assort_sc': 0,
         u'is_sku': u'Y',
         u'location_type': u'Primary Shelf',
         u'manufacturer_name': u'Mars',
         u'product_ean_code': u'4770608247003',
         u'product_english_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_fk': 761,
         u'product_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_short_name': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_type': u'CE',
         u'rlv_dist_sc': 1,
         u'rlv_oos_sc': 1,
         u'rlv_sos_sc': 1,
         u'scene_fk': 14984,
         u'scene_id': 14984,
         u'sub_brand_name': None,
         u'sub_category': u'Cat Superpremium',
         u'template_display_name': u'Petcare Main Shelves',
         u'template_group': None,
         u'template_name': u'Tesco BB Hypermarket',
         u'visit_date': datetime.date(2017, 5, 23)}]

    scene_item_facts_product_4770608247003_ce_dreamies_wrong_scene_type = [
        {u'brand_name': u'Dreamies',
         u'category_fk': 1,
         u'dist_sc': 1,
         u'facings': 2.0,
         u'facings_ign_stack': 2.0,
         'front_face_count': 1.0,
         u'gross_area_ign_stack': 34254.0,
         u'gross_area_split_stack': 35292.0,
         u'gross_len_add_stack': 173.0,
         u'gross_len_ign_stack': 173.0,
         u'gross_len_split_stack': 173.0,
         u'in_assort_sc': 0,
         u'is_sku': u'Y',
         u'location_type': u'Primary Shelf',
         u'manufacturer_name': u'Mars',
         u'product_ean_code': u'4770608247003',
         u'product_english_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_fk': 761,
         u'product_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_short_name': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_type': u'CE',
         u'rlv_dist_sc': 1,
         u'rlv_oos_sc': 1,
         u'rlv_sos_sc': 1,
         u'scene_fk': 14984,
         u'scene_id': 14984,
         u'sub_brand_name': None,
         u'sub_category': u'Cat Superpremium',
         u'template_display_name': u'wrong_scene_type',
         u'template_group': None,
         u'template_name': u'Tesco BB Hypermarket',
         u'visit_date': datetime.date(2017, 5, 23)}]

    scene_item_facts_product_4770608247003_4_facings = [
        {u'brand_name': u'Sheba',
         u'category_fk': 1,
         u'dist_sc': 1,
         u'facings': 4.0,
         u'facings_ign_stack': 2.0,
         'front_face_count': 1.0,
         u'gross_area_ign_stack': 34254.0,
         u'gross_area_split_stack': 35292.0,
         u'gross_len_add_stack': 173.0,
         u'gross_len_ign_stack': 173.0,
         u'gross_len_split_stack': 173.0,
         u'in_assort_sc': 0,
         u'is_sku': u'Y',
         u'location_type': u'Primary Shelf',
         u'manufacturer_name': u'Mars',
         u'product_ean_code': u'4770608247003',
         u'product_english_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_fk': 761,
         u'product_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_short_name': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_type': u'SKU',
         u'rlv_dist_sc': 1,
         u'rlv_oos_sc': 1,
         u'rlv_sos_sc': 1,
         u'scene_fk': 14984,
         u'scene_id': 14984,
         u'sub_brand_name': None,
         u'sub_category': u'Cat Superpremium',
         u'template_display_name': u'Petcare Main Shelves',
         u'template_group': None,
         u'template_name': u'Tesco BB Hypermarket',
         u'visit_date': datetime.date(2017, 5, 23)}]

    scene_item_facts_product_3065890099692 = [
         {u'brand_name': u'test',
          u'category_fk': 1,
          u'dist_sc': 1,
          u'facings': 2.0,
          u'facings_ign_stack': 2.0,
          'front_face_count': 1.0,
          u'gross_area_ign_stack': 34254.0,
          u'gross_area_split_stack': 35292.0,
          u'gross_len_add_stack': 173.0,
          u'gross_len_ign_stack': 173.0,
          u'gross_len_split_stack': 173.0,
          u'in_assort_sc': 0,
          u'is_sku': u'Y',
          u'location_type': u'Primary Shelf',
          u'manufacturer_name': u'Mars',
          u'product_ean_code': u'3065890099692',
          u'product_english_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
          u'product_fk': 761,
          u'product_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
          u'product_short_name': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
          u'product_type': u'SKU',
          u'rlv_dist_sc': 1,
          u'rlv_oos_sc': 1,
          u'rlv_sos_sc': 1,
          u'scene_fk': 14984,
          u'scene_id': 14984,
          u'sub_brand_name': None,
          u'sub_category': u'Cat Superpremium',
          u'template_display_name': u'Petcare Main Shelves',
          u'template_group': None,
          u'template_name': u'Tesco BB Hypermarket',
          u'visit_date': datetime.date(2017, 5, 23)}]

    scene_item_facts_product_3065890099692_ce_not_dreamies = [
        {u'brand_name': u'test',
         u'category_fk': 1,
         u'dist_sc': 1,
         u'facings': 2.0,
         u'facings_ign_stack': 2.0,
         'front_face_count': 1.0,
         u'gross_area_ign_stack': 34254.0,
         u'gross_area_split_stack': 35292.0,
         u'gross_len_add_stack': 173.0,
         u'gross_len_ign_stack': 173.0,
         u'gross_len_split_stack': 173.0,
         u'in_assort_sc': 0,
         u'is_sku': u'Y',
         u'location_type': u'Primary Shelf',
         u'manufacturer_name': u'Mars',
         u'product_ean_code': u'3065890099692',
         u'product_english_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_fk': 761,
         u'product_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_short_name': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_type': u'CE',
         u'rlv_dist_sc': 1,
         u'rlv_oos_sc': 1,
         u'rlv_sos_sc': 1,
         u'scene_fk': 14984,
         u'scene_id': 14984,
         u'sub_brand_name': None,
         u'sub_category': u'Cat Superpremium',
         u'template_display_name': u'Petcare Main Shelves',
         u'template_group': None,
         u'template_name': u'Tesco BB Hypermarket',
         u'visit_date': datetime.date(2017, 5, 23)}]

    scene_item_facts_product_5900951112935_dreamies_not_ce = [
        {u'brand_name': u'Dreamies',
         u'category_fk': 1,
         u'dist_sc': 1,
         u'facings': 2.0,
         u'facings_ign_stack': 2.0,
         'front_face_count': 1.0,
         u'gross_area_ign_stack': 34254.0,
         u'gross_area_split_stack': 35292.0,
         u'gross_len_add_stack': 173.0,
         u'gross_len_ign_stack': 173.0,
         u'gross_len_split_stack': 173.0,
         u'in_assort_sc': 0,
         u'is_sku': u'Y',
         u'location_type': u'Primary Shelf',
         u'manufacturer_name': u'Mars',
         u'product_ean_code': u'5900951112935',
         u'product_english_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_fk': 761,
         u'product_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_short_name': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_type': u'SKU',
         u'rlv_dist_sc': 1,
         u'rlv_oos_sc': 1,
         u'rlv_sos_sc': 1,
         u'scene_fk': 14984,
         u'scene_id': 14984,
         u'sub_brand_name': None,
         u'sub_category': u'Cat Superpremium',
         u'template_display_name': u'Petcare Main Shelves',
         u'template_group': None,
         u'template_name': u'Tesco BB Hypermarket',
         u'visit_date': datetime.date(2017, 5, 23)}]

    scene_item_facts_product_5900951112935 = [
        {u'brand_name': u'Sheba',
         u'category_fk': 1,
         u'dist_sc': 1,
         u'facings': 2.0,
         u'facings_ign_stack': 2.0,
         'front_face_count': 1.0,
         u'gross_area_ign_stack': 34254.0,
         u'gross_area_split_stack': 35292.0,
         u'gross_len_add_stack': 173.0,
         u'gross_len_ign_stack': 173.0,
         u'gross_len_split_stack': 173.0,
         u'in_assort_sc': 0,
         u'is_sku': u'Y',
         u'location_type': u'Primary Shelf',
         u'manufacturer_name': u'Mars',
         u'product_ean_code': u'5900951112935',
         u'product_english_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_fk': 761,
         u'product_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_short_name': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_type': u'SKU',
         u'rlv_dist_sc': 1,
         u'rlv_oos_sc': 1,
         u'rlv_sos_sc': 1,
         u'scene_fk': 14984,
         u'scene_id': 14984,
         u'sub_brand_name': None,
         u'sub_category': u'test',
         u'template_display_name': u'Petcare Main Shelves',
         u'template_group': None,
         u'template_name': u'Tesco BB Hypermarket',
         u'visit_date': datetime.date(2017, 5, 23)}]

    scene_item_facts_product_5900951113758 = [
        {u'brand_name': u'test',
         u'category_fk': 1,
         u'dist_sc': 1,
         u'facings': 2.0,
         u'facings_ign_stack': 2.0,
         'front_face_count': 1.0,
         u'gross_area_ign_stack': 34254.0,
         u'gross_area_split_stack': 35292.0,
         u'gross_len_add_stack': 173.0,
         u'gross_len_ign_stack': 173.0,
         u'gross_len_split_stack': 173.0,
         u'in_assort_sc': 0,
         u'is_sku': u'Y',
         u'location_type': u'Primary Shelf',
         u'manufacturer_name': u'Mars',
         u'product_ean_code': u'5900951113758',
         u'product_english_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_fk': 761,
         u'product_name': u'4770608247003 SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_short_name': u'SHEBA FRESH CHOICE FISH SELECTION IN GRAVY 50G X6',
         u'product_type': u'SKU',
         u'rlv_dist_sc': 1,
         u'rlv_oos_sc': 1,
         u'rlv_sos_sc': 1,
         u'scene_fk': 14984,
         u'scene_id': 14984,
         u'sub_brand_name': None,
         u'sub_category': u'Cat Superpremium',
         u'template_display_name': u'Petcare Main Shelves',
         u'template_group': None,
         u'template_name': u'Tesco BB Hypermarket',
         u'visit_date': datetime.date(2017, 5, 23)}]
