
__author__ = 'Idanr'


class Const(object):
    # Categories
    SNACKS = 'snacks'
    BEVERAGES = 'beverages'
    JUICES = 'juices'

    # Filters
    TEMPLATE_GROUP = 'template_group'
    CATEGORY = 'category'
    SUB_CATEGORY = 'sub_category'
    BRAND_NAME = 'brand_name'

    # KPI Names
    FACINGS_MANUFACTURER = 'FACINGS_SOS_BY_MANUFACTURER'
    FACINGS_LOCATION = 'FACINGS_SOS_BY_LOCATION'
    FACINGS_CATEGORY = 'FACINGS_SOS_BY_CATEGORY'
    FACINGS_SUB_CATEGORY = 'FACINGS_SOS_BY_SUB_CATEGORY'
    FACINGS_BRAND = 'FACINGS_SOS_BY_BRAND'
    LINEAR_MANUFACTURER = 'LINEAR_SOS_BY_MANUFACTURER'
    LINEAR_LOCATION = 'LINEAR_SOS_BY_LOCATION'
    LINEAR_CATEGORY = 'LINEAR_SOS_BY_CATEGORY'
    LINEAR_SUB_CATEGORY = 'LINEAR_SOS_BY_SUB_CATEGORY'
    LINEAR_BRAND = 'LINEAR_SOS_BY_BRAND'

