# import pandas as pd
#
#
# __author__ = 'israels'
#
# scene_template_head = {"template_name":{"0":"ADDITIONAL AMBIENT PLACEMENT","1":"ADDITIONAL AMBIENT PLACEMENT",
#                                    "2":"ADDITIONAL AMBIENT PLACEMENT","3":"ADDITIONAL AMBIENT PLACEMENT",
#                                    "4":"ADDITIONAL AMBIENT PLACEMENT"}}
#
# scene_template_complete = {"template_name":{"0":"ADDITIONAL AMBIENT PLACEMENT","1":"ADDITIONAL AMBIENT PLACEMENT","2":"ADDITIONAL AMBIENT PLACEMENT","3":"ADDITIONAL AMBIENT PLACEMENT","4":"ADDITIONAL AMBIENT PLACEMENT","5":"ADDITIONAL AMBIENT PLACEMENT","6":"ADDITIONAL AMBIENT PLACEMENT","7":"ADDITIONAL AMBIENT PLACEMENT","8":"ADDITIONAL AMBIENT PLACEMENT","9":"ADDITIONAL AMBIENT PLACEMENT","10":"CHILLED CASHIER COOLER PLACEMENT","11":"CHILLED CASHIER COOLER PLACEMENT","12":"CHILLED CASHIER COOLER PLACEMENT","13":"CHILLED CASHIER COOLER PLACEMENT","14":"CHILLED CASHIER COOLER PLACEMENT","15":"CHILLED CASHIER COOLER PLACEMENT","16":"CHILLED CASHIER COOLER PLACEMENT","17":"CHILLED CASHIER COOLER PLACEMENT","18":"CHILLED CASHIER COOLER PLACEMENT","19":"CHILLED CASHIER COOLER PLACEMENT","20":"CHILLED CASHIER COOLER PLACEMENT","21":"CHILLED CASHIER COOLER PLACEMENT","22":"CHILLED CASHIER COOLER PLACEMENT","23":"CHILLED CASHIER COOLER PLACEMENT","24":"CHILLED CASHIER COOLER PLACEMENT","25":"CHILLED CASHIER COOLER PLACEMENT","26":"CHILLED CASHIER COOLER PLACEMENT","27":"CHILLED CASHIER COOLER PLACEMENT","28":"CHILLED CASHIER COOLER PLACEMENT","29":"CHILLED CASHIER COOLER PLACEMENT","30":"CHILLED CASHIER COOLER PLACEMENT","31":"CHILLED CASHIER COOLER PLACEMENT","32":"CHILLED CASHIER COOLER PLACEMENT","33":"CHILLED CASHIER COOLER PLACEMENT","34":"CHILLED CASHIER COOLER PLACEMENT","35":"CHILLED CASHIER COOLER PLACEMENT","36":"CHILLED CASHIER COOLER PLACEMENT","37":"CHILLED CASHIER COOLER PLACEMENT","38":"CHILLED CASHIER COOLER PLACEMENT","39":"CHILLED CASHIER COOLER PLACEMENT","40":"CHILLED CASHIER COOLER PLACEMENT","41":"CHILLED CASHIER COOLER PLACEMENT","42":"CHILLED CASHIER COOLER PLACEMENT","43":"CHILLED CASHIER COOLER PLACEMENT","44":"ADDITIONAL CHILLED PLACEMENT","45":"ADDITIONAL CHILLED PLACEMENT","46":"ADDITIONAL CHILLED PLACEMENT","47":"ADDITIONAL CHILLED PLACEMENT","48":"ADDITIONAL CHILLED PLACEMENT","49":"ADDITIONAL CHILLED PLACEMENT","50":"ADDITIONAL CHILLED PLACEMENT","51":"MAIN PLACEMENT","52":"MAIN PLACEMENT","53":"MAIN PLACEMENT","54":"MAIN PLACEMENT","55":"MAIN PLACEMENT","56":"MAIN PLACEMENT","57":"MAIN PLACEMENT","58":"MAIN PLACEMENT","59":"MAIN PLACEMENT","60":"MAIN PLACEMENT","61":"MAIN PLACEMENT","62":"MAIN PLACEMENT","63":"MAIN PLACEMENT","64":"MAIN PLACEMENT","65":"MAIN PLACEMENT","66":"MAIN PLACEMENT","67":"MAIN PLACEMENT","68":"MAIN PLACEMENT","69":"MAIN PLACEMENT","70":"MAIN PLACEMENT","71":"MAIN PLACEMENT","72":"MAIN PLACEMENT","73":"MAIN PLACEMENT","74":"MAIN PLACEMENT","75":"MAIN PLACEMENT","76":"MAIN PLACEMENT","77":"MAIN PLACEMENT","78":"MAIN PLACEMENT","79":"MAIN PLACEMENT","80":"MAIN PLACEMENT","81":"MAIN PLACEMENT","82":"MAIN PLACEMENT","83":"MAIN PLACEMENT"}}
#
# atomic_kpi_fk = {"atomic_kpi_name":{"4":"K001","5":"K002","6":"K003","7":"K004","8":"K005"},"atomic_kpi_fk":
#     {"4":9,"5":10,"6":11,"7":12,"8":13},"kpi_name":{"4":"Shelf occupation","5":"Shelf occupation","6":"Shelf occupation","7":"Shelf occupation","8":"Shelf occupation"},"kpi_fk":{"4":3,"5":3,"6":3,"7":3,"8":3},"kpi_set_name":{"4":"Shelf occupation","5":"Shelf occupation","6":"Shelf occupation","7":"Shelf occupation","8":"Shelf occupation"},"kpi_set_fk":{"4":3,"5":3,"6":3,"7":3,"8":3}}
#
#
# def get_scene_data_head():
#         return pd.DataFrame(scene_template_head)
#
#
# def get_scene_data_complete():
#         return pd.DataFrame(scene_template_complete)
#
#
# def get_atomic_fk():
#     return pd.DataFrame(atomic_kpi_fk)
