class Consts(object):
    SHELF_MAP = 'shelf_map'
    SHARE_OF_SCENES = 'Share of Scenes'
    SCENE_LOCATION = 'Scene Location'
    SHELF_POSITION = 'Shelf Position'
    BLOCKING = 'Blocking'
    BAY_POSITION = 'Bay Position'
    DIAMOND_POSITION = 'Diamond Position'
    KPI_TYPE = 'kpi_type'
    KPI_NAME = 'kpi_client_name'
    FINAL_FACINGS = 'final_facings'
    DISTRIBUTION = 'Distribution'
    KPI_TYPE = 'kpi_type'
    ACTUAL_TYPE = 'KPI Type'
    # SCENE_FK = 'scene_fk